// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzrlsclgicmrgdjqmrdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6cmxzY2xnaWNtcmdkanFtcmR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMjg5MTIsImV4cCI6MjA2NzkwNDkxMn0.FyaktPByWXfQA43iIkCXi_9jrNfPeshLkMCK1ugc-eA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});